server.servlet.context-path=/prosta
server.port=7778
spring.thymeleaf.cache=false

spring.mvc.format.date=yyyy/MM/dd

#DB 設定
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#↓下記変更箇所、先頭の#を消し、AWS の環境に合わせて、xxxx.の部分を変更し、コメントを外す
spring.datasource.url=jdbc:oracle:thin:oracleadmin/IZ3iK0snhodolV8m4rA3@deployhandsonoracleinstance20260616.cv8emkiaytj6.ap-northeast-1.rds.amazonaws.com:1521:oracledb

